import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/navbars/TopNav";
import { Sidebar } from "@/components/navbars/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-[#030303] text-zinc-100">
        <TopNav />
        <div className="flex min-h-[calc(100vh-3rem)]">
          <Sidebar />
          <main className="ml-60 flex w-full h-full min-h-[calc(100vh-56px)] px-4 py-4 ">{children}</main>
        </div>
      </body>
    </html>
  );
}
